@echo off
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Blocks\Floor with gap 30x146.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Blocks\Grass 42x54.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Blocks\Grass with statue 12x12.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Blocks\RoadA corner with outwards sidewalk 20x20.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Blocks\RoadA junction with two sidewalks 26x26.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Blocks\RoadA Straight with two sidewalks 96x28.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\Floor with centre stud 2Lx2Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\Floor with gap 30x146.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 1x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 1x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 2x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 3x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 3x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 3x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 4x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 4x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 6x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 6x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA 6x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\FloorA-1 6x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\Grass 42x54.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\Grass with statue 12x12.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\RoadA corner with outwards sidewalk 20x20.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\RoadA junction with two sidewalks 26x26.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\RoadA Straight with two sidewalks 96x28.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\RoadLineA 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\RoadLineA Corner 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\Wall2LThicKA Double Shingled 2x16.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\Wall2LThicKA Shingled 2x20.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallA 1Lx1Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallA 1Lx1Lx2P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallA 1Lx1Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallA 1Lx1Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallA 1Lx6Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallB 2LX1Lx2B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallB 2LX1Lx3B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallB 4LX1Lx3B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Detatch\WallB 8LX1Lx6B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\Banister 1Lx6Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\Pillar round 1Lx1Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\WallK with 8 windows 1Lx6Lx29P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\BenchA\BenchA 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\Chairs\DeskChair 3x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\Pillars\Pillar with rounded top 1Lx1Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Precolored\PlanterA\PlanterA 2x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Banister 1Lx6Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Pillar round 1Lx1Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\WallK with 8 windows 1Lx6Lx29P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\BenchA\BenchA 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Chairs\ChairA 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Chairs\DeskChair 3x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Crates\Crate open top 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cuboard 2Lx3Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cupboard 2Lx3Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cupboard 2Lx3Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cupboard 2Lx6Lx18P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cupboard 3Lx6Lx18P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cupboard with side studs 2Lx6Lx18P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Cupboards\Cupboard with side studs 3Lx6Lx18P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Fence\FenceA 4Lx6L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Fence\FenceSnot 8Lx16L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Fence\FenceSnot 8Lx24L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Fence\FenceSnot 8Lx32L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Fence\FenceSnot 8Lx8L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Fence\FenceSnot corner 8Lx8L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\Floor 2L x 2L x 1P Psychedelic\Floor Psychedelic 2Lx2Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\Floor 6L x 6L x 1P Shingled\Floor Shingled 6Lx6Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\Floor with centre stud 2Lx2Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\1x\FloorA 1x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\2x\FloorA 2x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\3x\FloorA 3x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\4x\FloorA 4x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\5x\FloorA 5x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\6x\FloorA 6x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\7x\FloorA 7x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\8x\FloorA 8x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x1.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x5.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorA\9x\FloorA 9x9.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorTiledFlagstoneA 4x4\FloorTiledFlagstoneA 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorTiledFlagstoneB 4x4\FloorTiledFlagstoneB 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorTiledMirror 4x4\FloorTiledMirror 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Floor\FloorTiledPink 4x4\FloorTiledPink 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx10Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx12Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx13Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx15Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx1Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx2Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx3Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx4Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx6Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx7Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Handrails\BanisterA 1Lx9Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Panel\Panel with top lip 1Lx1.3Lx1B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Panel\Panel with top lip 2Lx1.3Lx4.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Pillars\Pillar with rounded top 1Lx1Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\PlanterA\PlanterA 2x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\Mushroom A 3x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\Mushroom A 4x4.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\Mushroom B 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\Mushroom B 3x3.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\Mushroom B inverted 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\MushroomA 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\MushroomA inverted 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\MushroomA short 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Plants\Mushroom\MushroomB short 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Road Lines\RoadLineA 2x6\RoadLineA 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Road Lines\RoadLineA Corner 2x2\RoadLineA Corner 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Road Lines\RoadLineB 2x6\RoadLineB 2x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\RoadDrain 2x2\RoadDrain 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Signs\Sign Electricity 2x2\Sign Electricity 2x2.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Sofas\Sofa A 3x7.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Tables\table 6x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Tables\table 6x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Tables\table 8x12.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Tables\table round 6x6.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Tables\table round 6x8.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\Wall2LThicKA 2x16 DoubleShingled\Wall2LThicKA DoubleShingled 2x16.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\Wall2LThicKA 2x20 Shingled\Wall2LThick  Shingled A 2x20.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 10L\WallA 1Lx10Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 12L\WallA 1Lx12Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx10P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx11P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx13P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx14P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx2P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx8P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 1L\WallA 1Lx1Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx10P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx11P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx13P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx14P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx2P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx8P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 2L\WallA 1Lx2Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx10P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx11P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx13P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx14P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx2P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx8P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 3L\WallA 1Lx3Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx10P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx11P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx13P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx14P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx2P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx4P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx7P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx8P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 4L\WallA 1Lx4Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 5L\WallA 1Lx5Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 6L\WallA 1Lx6Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallA\1L x 8L\WallA 1Lx8Lx1P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallB\_L x 1L x _B\WallB 2LX1Lx2B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallB\_L x 1L x _B\WallB 2LX1Lx3B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallB\_L x 1L x _B\WallB 4LX1Lx3B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallB\_L x 1L x _B\WallB 6LX1Lx5B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallB\_L x 1L x _B\WallB 8LX1Lx6B.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 2L x _P\WallC 1Lx2Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 2L x _P\WallC 1Lx2Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 2L x _P\WallC 1Lx2Lx18P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 2L x _P\WallC 1Lx2Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 2L x _P\WallC 1Lx2Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 4L x _P\WallC 1Lx4Lx12P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 4L x _P\WallC 1Lx4Lx15P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 4L x _P\WallC 1Lx4Lx18P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 4L x _P\WallC 1Lx4Lx6P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x 4L x _P\WallC 1Lx4Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx10Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx12Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx14Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx16Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx2Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx4Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx6Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallC\1L x _L x 3P\WallC 1Lx8Lx3P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx10L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx12L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx14L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx16L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx18L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx2L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx4L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx6L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Centre\WallD centred 2Lx1Lx8L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx10L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx12L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx14L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx16L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx18L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx2L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx4L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx6L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\1L x 2L x _L double high\WallD down double high 1Lx2Lx8L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\2L x 1L x _\WallD down 2Lx1Lx11.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\2L x 1L x _\WallD down 2Lx1Lx14.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\2L x 1L x _\WallD down 2Lx1Lx17.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\2L x 1L x _\WallD down 2Lx1Lx1L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\2L x 1L x _\WallD down 2Lx1Lx5.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\2L x 1L x _\WallD down 2Lx1Lx8.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _\WallD down 4Lx1Lx11.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _\WallD down 4Lx1Lx14.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _\WallD down 4Lx1Lx17.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _\WallD down 4Lx1Lx1L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _\WallD down 4Lx1Lx5.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _\WallD down 4Lx1Lx8.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD  down double high 4Lx1Lx10L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx12L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx14L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx16L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx18L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx2L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx4L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx6L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Down\4L x 1L x _L double high\WallD down double high 4Lx1Lx8L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx10L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx12L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx16L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx18L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx2L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx4L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx6L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\1L x 2L x _L\WallD up 1Lx2Lx8L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\2L x 1L x _\WallD up 2Lx1Lx11.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\2L x 1L x _\WallD up 2Lx1Lx14.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\2L x 1L x _\WallD up 2Lx1Lx17.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\2L x 1L x _\WallD up 2Lx1Lx1L.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\2L x 1L x _\WallD up 2Lx1Lx5.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Wall\WallD\Up\2L x 1L x _\WallD up 2Lx1Lx8.5P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Windows\Window 1Lx2Lx9P.ldr"
call builder.bat "C:\Users\kris\Desktop\LS\TLG_Map\Testmap2\Shared\Windows\Window 1Lx3Lx9P.ldr"
cmd /k